### ISSUE TITLE
inconsistent time vector for semantic test case 01395

### ISSUE THREAD

**Issue by FFroehlich** [sbmlteam/sbml-test-suite#49]
settings.txt: 
```
steps: 100
```

results.csv:
```
time
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1

```

**Comment by luciansmith** [comment]
Whoops; you're exactly correct.  Updated to 100 points, and to match roadrunner's output.  Let me know if you get different results and think they should be correct.

**Comment by FFroehlich** [comment]
The updated results match my simulation results! Great!
