### ISSUE TITLE
Problems converting ASTNode2 to ASTNode with FormulaParserLL3

### ISSUE THREAD

**Issue by LisaFalk** [sbmlteam/sbml-test-suite#53]
Even though it is not the best idea converting ASTNode2 to ASTNode with FormulaParserLL3 we thought it would be working. 
But the formula (A xor B) causes the following exception: 
Caused by: org.sbml.jsbml.text.parser.ParseException: Encountered " <STRING> "xor "" at line 1, column 3.
Was expecting one of:
    <EOF> 
    "+" ...
    "^" ...
    "-" ...
    "*" ...
    "/" ...
    "%" ...
    <COMPARISON> ...
    <BOOLEAN_LOGIC> ...
    <EOL> ...

**Comment by mhucka** [comment]
Hi @LisaFalk – thanks for the note, but I'm not sure I understand why this issue is noted here, in the test suite repository. This sounds like a problem with JSBML. Should the issue perhaps be opened in the JSBML repo?

**Comment by LisaFalk** [comment]
That' a correct objection! It should be opened in the JSBML repo.
