### ISSUE TITLE
Integrate new distrib stochastic test cases

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/sbml-test-suite#56]
Lucian has created a [bunch of test cases](https://github.com/luciansmith/stochastic-distrib-test-suite) for the SBML `distrib` package. These should be incorporated into the main test suite.

Steps include at least the following:

- [ ] incorporate the files from Lucian's repo
- [ ] rewrite the [README file in the stochastic subdirectory](https://github.com/sbmlteam/sbml-test-suite/tree/develop/cases/stochastic) because the contents will no longer be solely from the DSMTS
- [ ] add instructions for using the new cases
- [ ] create a new test cases release

**Comment by luciansmith** [comment]
Well, step 1 is 'ensure that the expected results are accurate'.   And, I suppose, there's also the possibility that some of the csymbols being tested in that suite will not end up in the final version of the package, if nobody implements support for them.

**Comment by luciansmith** [comment]
These are now released!
