### ISSUE TITLE
Update screenshots of STS on sbml.org

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/sbml-test-suite#61]
The screenshots on http://sbml.org/Software/SBML_Test_Suite/SBML_Test_Suite_Screenshots are out of date.

**Comment by luciansmith** [comment]
That URL no longer exists, and the screenshot of the test runner that does show up in a couple places (including https://sbml.org/software/sbml-test-suite/) seems to be correct.  I think we can close this.
