### ISSUE TITLE
Leading whitespaces in results.csv

### ISSUE THREAD

**Issue by FFroehlich** [sbmlteam/sbml-test-suite#71]
Some results.csv files contain leading whitespaces in the variable names, for example ` S1` in

https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/master/cases/semantic/00998/00998-results.csv

This also happens in the testcases 1122, 1123.

**Comment by mhucka** [comment]
Thanks for pointing this out. 

@luciansmith do you think would there be any problem if we simply ran a quick `sed` command to clean up the leading spaces across all the test caes? I could do that pretty easily.

**Comment by luciansmith** [comment]
That would be perfect.  Thank you!

**Comment by mhucka** [comment]
Fix in commit 23eed807665d205f1a5a7fb09cd17a381f73ef07.

**Comment by luciansmith** [comment]
Fixed.
