### ISSUE TITLE
Test Runner crash with params named 'Time'.

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-test-suite#74]
I created a couple tests for parameters named 'time', 'Time' and 'TIME', and they crash the test suite runner when I run them and then click on them to view the results.

[params_named_time.zip](https://github.com/sbmlteam/sbml-test-suite/files/5447929/params_named_time.zip)

**Comment by fbergmann** [comment]
I do not get the crash ... do you have any more information on it?

![image](https://user-images.githubusercontent.com/949059/108985799-bf7e6800-7691-11eb-995e-87ef4d2453a7.png)

**Comment by luciansmith** [comment]
I went to test this, but the SBML Runner no longer runs on my computer at all.  It says it wants java 1.6, and takes me to the download page for java, which I installed, but the runner still complains about needing 1.6.  Maybe the problem is that 1.18 or whatever is a lower *number* than 1.6?

**Comment by mhucka** [comment]
What does the 1.18 refer to in your message above?

**Comment by luciansmith** [comment]
It was just a guess as to what version of java I installed, since the installer won't tell you.

**Comment by mhucka** [comment]
There is no version 1.18 of Java, so this is immediately suspect. I don't think you actually installed Java :-). What did you install exactly? Where did you get it from? And finally, what operating system are you running? I'll try to help find an actual Java installation but need a bit more info.

**Comment by luciansmith** [comment]
No, sorry, as I say, the JRE installer will not tell me what version of Java it installed; that's just the way java rolls; they don't want you to know what version you have.  I installed it from Oracle for Windows 64-bit, aka jre-8u311-windows-x64.exe

**Comment by fbergmann** [comment]
Ok, you are using java 1.8 patch 311. That is fine, i'm running 1.8 here as well (just the jdk instead of the jre). What precise error message are you getting?

**Comment by luciansmith** [comment]
OK!  The problem was indeed that I had downloaded the 64-bit version, which won't work.  The 32-bit version worked fine.

And I'm getting the crash again:  I click on '1820' or '1821' and the whole window disappears with no error message or anything.  Might there be a log file somewhere?

**Comment by luciansmith** [comment]
I found C:\Users\Lucian\AppData\LocalLow\Sun\Java\Deployment\log but it was empty, and similarly, C:\Program Files (x86)\SBML\SBML Test Runner\ has no added information there, either.  If there's something else I can do to try to capture what's going on, I'm happy to do so.

**Comment by fbergmann** [comment]
i've not been trying any of the installers. since you have the repo checked out already, you should be able to just change to the testrunner-ui directory and run:  

``` 
ant build
ant start-win-64
```

does that work for you (cause thats what i was doing)

**Comment by luciansmith** [comment]
I can run 'ant build' on ubuntu, but not on Windows--cygwin doesn't have ant, and it doesn't seem to have come with java.  The installation instructions look a little daunting, but I can try if you think it'll help.

**Comment by fbergmann** [comment]
I'm using [chocolatey](https://chocolatey.org) as package manager on windows, with that installing ant is just `choco install ant`, after that you just change into the directory and should be ready to run it.

**Comment by luciansmith** [comment]
OK, after installing java, the java dev kit, chocolatey, and ant, I now get:

PS C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui> ant build
Buildfile: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build.xml

build-subprojects:
     [echo] Building dependent subproject
     [echo] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui/../testsuite-core

init:

build-subprojects:

build-project:
    [javac] Compiling 22 source files to C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-core\build
    [javac] Note: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-core\src\org\sbml\testsuite\core\Util.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

build:

jar:
      [jar] Building jar: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-core\dist\testsuite-core.jar

init:
    [mkdir] Created dir: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\dist
    [mkdir] Created dir: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build
    [mkdir] Created dir: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build\classes

build-project:
     [echo] Now building testsuite-ui
     [echo] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build.xml
    [javac] Compiling 43 source files to C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build\classes
    [javac] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\src\org\sbml\testsuite\ui\CocoaUIEnhancer.java:337: warning: [removal] Long(long) in Long has been deprecated and marked for removal
    [javac]             return new Long(value);
    [javac]                    ^
    [javac] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\src\org\sbml\testsuite\ui\CocoaUIEnhancer.java:341: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
    [javac]             return new Integer((int) value);
    [javac]                    ^
    [javac] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\src\org\sbml\testsuite\ui\PollingFileWatcher.java:132: warning: [removal] Long(long) in Long has been deprecated and marked for removal
    [javac]             files_.put (file, new Long(modifiedTime));
    [javac]                               ^
    [javac] C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\src\org\sbml\testsuite\ui\PollingFileWatcher.java:306: warning: [removal] Long(long) in Long has been deprecated and marked for removal
    [javac]                     files_.put(file, new Long(newModifiedTime));
    [javac]                                      ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 4 warnings

build:

BUILD SUCCESSFUL
Total time: 4 seconds
PS C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui> ant start-win-64
Buildfile: C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\build.xml

swt-win-64:

start-win-64:
     [java] Error: Unable to access jarfile C:\Users\Lucian\Desktop\sbml-test-suite\src\test-runner\testsuite-ui\dist\sbmltestrunner.jar
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 0 seconds

**Comment by luciansmith** [comment]
OK!  With Frank's help, we figured out what was going on on my machine to make it crash, and this has been fixed with https://github.com/sbmlteam/sbml-test-suite/commit/62be5b01048c75779e18ea89e6f389b77ca3f8c8

It still doesn't handle 1820 and 1821 as ideally as it could, but 'not crashing' is great and is fine for now.  I'll file a new one for the remainder.
