### ISSUE TITLE
SBMLTestRunner crashes on start-up with "Empty wrapper selection"

### ISSUE THREAD

**Issue by eltix** [sbmlteam/sbml-test-suite#75]
## Issue description

After installing the SBMLTestRunner executable using the Linux 64-bit runnable installer found [here](https://github.com/sbmlteam/sbml-test-suite/releases), the application crashes on start-up with the "Empty wrapper selection" error message (see screenshot below)
![image](https://user-images.githubusercontent.com/28726150/108973525-baff8280-7684-11eb-892c-e265bb767d41.png)

I tried several times deleting the application and installing it from scratch, to no avail.

## Console logs
```
~/SBMLTestRunner-3.3.0/bin » ./SBMLTestRunner-linux-x64                                                                                             etixier@campus029:37:32
java.lang.NullPointerException
	at org.sbml.testsuite.ui.MainWindow.changeWrapper(MainWindow.java:877)
	at org.sbml.testsuite.ui.MainWindow.access$200(MainWindow.java:109)
	at org.sbml.testsuite.ui.MainWindow$WrapperMenuListener.select(MainWindow.java:163)
	at org.sbml.testsuite.ui.MainWindow.updateWrapperList(MainWindow.java:2991)
	at org.sbml.testsuite.ui.MainWindow.loadModel(MainWindow.java:2649)
	at org.sbml.testsuite.ui.MainWindow.open(MainWindow.java:2841)
	at org.sbml.testsuite.ui.Program.main(Program.java:58)
```

**Comment by fbergmann** [comment]
Sorry for the inconvenience, if found the offending line and fixed it for a future release, though there is currently no timeline for this. But i've tried a local installation and  if you move your current installation out of the way: 

`mv ~/.testsuite.xml ~/.testsuite.xml_old`

And then start the user interface again, you get the initial configuration dialog. At that point it is important, to either specify a wrapper, or disable the option 

![image](https://user-images.githubusercontent.com/949059/108984234-fb183280-768f-11eb-96c1-6d2c5773c1ce.png)

and click the save button (click that one in any case). The only way to trigger the exception is to hit escape on the dialog on my machine.

**Comment by eltix** [comment]
@fbergmann Thanks for your swift reply that fixed it indeed! I assumed it had something to do with a local config file but could not locate it.

**Comment by luciansmith** [comment]
Closing this, as a fix is in the works, and a workaround was found. Thanks again for the report!
