### ISSUE TITLE
Can't run this app on MacOS(M2 Ventura 13.2.1).

### ISSUE THREAD

**Issue by tyzerrr** [sbmlteam/sbml-test-suite#91]
Hey, all!
I installed binary version of this app v3.4.0, and double-click the icon, but app didn't start.
After that, I tried previous version, v3.3.0, but it didn't work well.
Of course, I have local java environment, and I checked the doc, but I can't find any of pre-requirements for launching this app.
Any help?

**Comment by fbergmann** [comment]
Indeed, the SWT version of the binary (since they were created in intel / ppc  times), probably would not run for you locally. You'd need at least an SWT version. (or there might be a command line switch running java in x64 mode) We would have to prepare a new binary, but this might take a while. For now it would be possible to run the command line version. Would that work for you?

**Comment by tyzerrr** [comment]
Thank you for answering my issue, Frank!

Probably, what you meant is to clone this repo to my local env, and I'm gonna to compile the source like this link(https://github.com/sbmlteam/sbml-test-suite/tree/release/src/test-runner/testsuite-ui).

**I tried this way like below, but I faild to make jar with ant.
Here are commands I entered and log.  I'm not sure what "multimarkdown" is, but probably this is the source of this problem.**

`git clone https://github.com/sbmlteam/sbml-test-suite`
`cd sbml-test-suite/src/test-runner/testsuite-ui`
`set TESTRUNNER_IGNORE_HELP=true`
`set TESTRUNNER_IGNORE_ARCHIVE=true`
`ant build`

> BUILD FAILED
> /Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/build.xml:426: The following error occurred while executing this line:
> /Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/build.xml:432: The following error occurred while executing this line:
> /Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/build.xml:312: The following error occurred while executing this line:
> /Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/docs/help-system/build.xml:23: The following error occurred while executing this line:
> /Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/docs/help-system/build.xml:39: Execute failed: java.io.IOException: Cannot run program "multimarkdown" (in directory "/Users/araki/dev/sbml-test-suite/src/test-runner/testsuite-ui/docs/help-system"): error=2, No such file or directory
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:594)
> 	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
> 	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
> 	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
> 	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
> 	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
> 	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at java.base/java.util.Vector.forEach(Vector.java:1365)
> 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.Target.execute(Target.java:449)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
> 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
> 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.Target.execute(Target.java:449)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
> 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
> 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
> 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.Target.execute(Target.java:449)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
> 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
> 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
> 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.Target.execute(Target.java:449)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
> 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
> 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
> 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
> 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
> 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
> 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
> 	... 78 more
> 
> Total time: 1 second

Sorry for my non-matured issue...

**Comment by fbergmann** [comment]
I've updated the build files to include the new SWT version, with that with openjdk and ant from homebrew it works with the following commands: 

```bash
git clone https://github.com/sbmlteam/sbml-test-suite
git checkout develop
cd sbml-test-suite/src/test-runner/testsuite-ui
export TESTRUNNER_IGNORE_HELP=true
export TESTRUNNER_IGNORE_ARCHIVE=true
export JAVA_HOME=/opt/homebrew/opt/openjdk/
ant build
ant jar-mac-arm
ant start-osx-arm
```

**Comment by tyzerrr** [comment]
It worked well! Thank U for great help! Love U!

**Comment by luciansmith** [comment]
This looks fixed?  Closing, but feel free to re-open if there are any lingering issues.
